### PR TITLE
`playwright_request.headers["user-agent"]` was not replaced for some …

### PR DESCRIPTION
**Pull request by clippered**
…reason, so return a new dict instance with replaced `user-agent`

### CODE REVIEW

**Comment by clippered** [comment]
@elacuesta not sure if github actions is running the test.
Anyway, for some reason `playwright_request.headers["user-agent"]` was not replaced in that line.
I tried repacking the dict and replace it with scrapy `headers["user-agent"]`
I hope this is ok.

**Comment by elacuesta** [comment]
Thanks for the contribution! The change seems harmless, but I don't really understand its motivation. Are you encountering problems with the current version? If so, please provide a [minimal and reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by clippered** [comment]
Thanks. An example is scraping this page https://www.binance.com/en/markets with headless chrome and override the scrapy's `user-agent` headers with a value (`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36`)
And print out the headers:
```
if headers.get("user-agent"):
    playwright_request.headers["user-agent"] = headers["user-agent"]
    print('TEST', playwright_request.headers["user-agent"], headers["user-agent"])
return playwright_request.headers
```
The first printed line will `Chrome` but the next lines show `HeadlessChrome`:
```
TEST Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/101.0.4929.0 Safari/537.36 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
TEST Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/101.0.4929.0 Safari/537.36 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/101.0.4929.0 Safari/537.36
TEST Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/101.0.4929.0 Safari/537.36 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/101.0.4929.0 Safari/537.36
...
```
Looks weird to me too, but I hope this example is enough.

**Comment by elacuesta** [comment]
Oh that makes a lot of sense, thanks for the explanation. However, I will be pushing a patch to use the [new headers API](https://playwright.dev/python/docs/release-notes#version-115) soon, that will supersede this change.

**Pull request merged**
